os: linux
dist: focal
language: node_js
node_js:
  - 15

before_install:
  - npm --version

install:
  - npm install

jobs:
  include:
    - stage: test
      script:
        - npm run test
  # - stage: lint
  #   script:
  #     - ./node_modules/eslint/bin/eslint.js --version
  #     - npm run lint
